# -*- coding: utf-8 -*-
"""python_exercicios_aula08

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WPkKztfOkxADM67mz4ZVyby9CexlWyGe
"""

EXERCICIOS AULA 08

1 -  Crie uma tupla chamada `frutas` com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.

frutas = ('maça','pera','uva','melão','banana')
terceiro=frutas[2]
print(terceiro)

bolsa 2 - Crie uma tupla chamada `numeros` com alguns números inteiros. Em seguida, converta essa tupla em uma lista e imprima a lista resultante.

numeros = (1,2,3,4,5,)
lista=list(numeros)
print(lista)


3 - Crie uma tupla chamada `meses` com os nomes dos meses do ano até Setembro. Use um loop `for` para imprimir cada mês em uma linha separada.

meses=('Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro')
for n in meses:
    print(n)

4 - Crie uma lista chamada `notas` com algumas notas de alunos. Em seguida, converta essa lista em uma tupla e imprima a tupla resultante.
notas=[7,9,6,7]
tuples = tuple(notas)
print(tuples)

5 - Crie uma lista chamada `ponto` que represente as coordenadas (x, y) de um ponto. Em seguida, desempacote os elementos da tupla em duas variáveis separadas (x e y) e imprima os valores.

ponto=(3,7) #desempacotar os valores
x,y=ponto
print(f'''eixo x ={x}
eixo y ={y}
''')